version: "3.9"

networks:
  db-development: 
    driver: bridge
    name: db-development

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "opravilo"
      POSTGRES_PASSWORD: "2282"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - db-development